name: Build Executable

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create Executable
      uses: sayyid5416/pyinstaller@v1
      with:
        python_ver: '3.8'
        spec: 'generate_complete_changelog.spec'
        requirements: 'requirements.txt'
        upload_exe_with_name: 'generate_complete_changelog.exe'
        options: --onefile, --name "generate_complete_changelog"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: generate_complete_changelog_windows_${{ github.run_id }}
        path: dist/generate_complete_changelog.exe

  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create Executable
      uses: sayyid5416/pyinstaller@v1
      with:
        python_ver: '3.12'
        spec: 'generate_complete_changelog.spec'
        requirements: 'requirements.txt'
        upload_exe_with_name: 'generate_complete_changelog'
        options: --onefile, --name "generate_complete_changelog"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: generate_complete_changelog_macos_${{ github.run_id }}
        path: dist/generate_complete_changelog

  create-release:
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/generate_complete_changelog_windows_${{ github.run_id }}/generate_complete_changelog.exe
          dist/generate_complete_changelog_macos_${{ github.run_id }}/generate_complete_changelog
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}